import '@/styles/globals.css';
import { Poppins } from 'next/font/google';
import { Toaster } from 'react-hot-toast';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800'],
  display: 'swap',
  variable: '--font-poppins',
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
  authors: [{ name: 'Sebastian Mena' }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={poppins.className}>
        {children}
        <Toaster position='top-right' reverseOrder={false} />
      </body>
    </html>
  );
}
